"""Shared visual language for the CSF PAB apps.

GENERATED by build_ict_ui.py from the NIPUN app's dashboard.py. Do not
edit this file directly. Change dashboard.py and regenerate, so the two
apps cannot drift apart.

The rules this file encodes, all of them learned rather than chosen
(PAB/CLAUDE.md section 10):
- Three faces, three jobs, no overlap. Instrument Serif carries
  headlines and nothing else, Inter Tight carries every word of running
  text, label and control, JetBrains Mono carries every digit that
  means something. All three load from Google Fonts, because Streamlit
  Cloud runs Linux with no licensed faces and a system-serif fallback
  there lands on DejaVu.
- The canvas is a cool near-white, not a warm cream. The brand navy and
  yellow are the only saturated things on the page and a warm ground
  fights the navy and muddies the yellow.
- The ink ramp has four steps and they are not interchangeable. MUTED is
  furniture only. Anything a reader actually reads, captions included,
  sits at QUIET or darker.
- Structure is hairlines and tinted surfaces, never shadow.
- Every section is a `with section(label, tone)` block. The tone reaches
  the panel through CSS :has(), because Streamlit owns the wrapper and
  gives no hook to put a class on it.
"""
import re
from contextlib import contextmanager

import pandas as pd
import streamlit as st

# ---- palette. A cool neutral canvas, not a warm cream one: the brand navy
# and yellow are the only saturated things on the page, and a warm ground
# fights the navy and muddies the yellow. Structure is carried by hairlines
# and by the white of the surfaces, never by shadow.
PAPER, CARD = "#fafafa", "#ffffff"
# Four steps of ink, each with a job. MUTED is deliberately light and is for
# furniture only (axis values, eyebrows, chart labels); anything a reader has
# to actually read, captions included, sits at QUIET or darker, because
# zinc-400 on a near-white ground is below comfortable reading contrast.
INK, INK2, QUIET, MUTED = "#0a0a0a", "#52525b", "#71717a", "#a1a1aa"
GRID, BASELINE, CHALK = "#e4e4e7", "#d4d4d8", "#f4f4f5"
# CSF_BLUE / CSF_YELLOW are the foundation's brand colors and lead the series;
# the rest carry no brand meaning and exist to separate categories.
CSF_BLUE, CSF_YELLOW = "#00316b", "#ffd400"
SERIES = [CSF_BLUE, CSF_YELLOW, "#3b82f6", "#f59e0b", "#ec4899",
          "#10b981", "#71717a"]
SEQ0 = "#dbeafe"  # palest step of the sequential ramp that ends at CSF_BLUE
SEQ = [SEQ0, "#93c5fd", "#60a5fa", "#2563eb", CSF_BLUE]
STATUS = {"good": "#16a34a", "warning": "#eab308",
          "serious": "#f97316", "critical": "#dc2626"}
# Section tones. Each is (surface wash, border, label and rule colour), built
# on the Scouted formula: the hue at a few percent for the fill, the same hue
# at mid alpha for the stroke, and a darkened version for type so the label
# stays readable at 0.68rem. Colour is assigned by what a section is about,
# not decoratively, so the same head keeps the same hue across tabs.
TONES = {
    "navy":    ("rgba(0,49,107,0.030)",   "rgba(0,49,107,0.20)",   "#00316b"),
    "gold":    ("rgba(255,212,0,0.070)",  "rgba(255,212,0,0.60)",  "#8a6d00"),
    "blue":    ("rgba(59,130,246,0.038)", "rgba(59,130,246,0.26)", "#1d4ed8"),
    "emerald": ("rgba(16,185,129,0.035)", "rgba(16,185,129,0.26)", "#047857"),
    "amber":   ("rgba(245,158,11,0.045)", "rgba(245,158,11,0.30)", "#b45309"),
    "pink":    ("rgba(236,72,153,0.032)", "rgba(236,72,153,0.24)", "#be185d"),
    "plain":   ("#ffffff",                "#e4e4e7",               "#71717a"),
}
# Three faces, three jobs, no overlap. A display serif carries the headlines
# and nothing else; a tight grotesque carries every word of running text,
# label and control; a monospace carries every digit, so figures align in a
# column and read as measured rather than written. All three are Google
# Fonts because Streamlit Cloud runs Linux with no licensed faces installed,
# and a system-serif fallback there lands on DejaVu, which is what made the
# previous build read as a default rather than a decision.
DISPLAY = '"Instrument Serif", "Iowan Old Style", Georgia, serif'
SANS = '"Inter Tight", Inter, system-ui, -apple-system, sans-serif'
MONO = '"JetBrains Mono", ui-monospace, "SF Mono", Menlo, monospace'


def inject_css():
    """Apply the story page's typography and card treatment to Streamlit.

    Kept additive on purpose. These are [data-testid] / [data-baseweb]
    hooks rather than a supported API, so a Streamlit release can rename
    one; when that happens the rule simply stops applying and the element
    falls back to default styling rather than disappearing.
    """
    # A bordered st.container renders as stVerticalBlock sitting directly
    # inside an stLayoutWrapper. The parent restriction matters: bare
    # stVerticalBlock is also the generic block element and would tint the
    # whole page. Columns and expanders nested inside a section do not
    # contain its eyebrow, so :has() cannot leak the tint down into them.
    wrap = ('[data-testid="stLayoutWrapper"] > '
            '[data-testid="stVerticalBlock"]')
    TONE_CSS = "\n".join(
        f"{wrap}:has(.tone-{name}) {{"
        f" background: {bg}; border-color: {bd} !important; }}\n"
        f".eyebrow.tone-{name} {{ color: {ac}; }}"
        for name, (bg, bd, ac) in TONES.items())
    st.markdown(f"""
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Instrument+Serif:ital@0;1&family=Inter+Tight:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;600&display=swap');

    .stApp {{ background: {PAPER}; }}
    html, body, [data-testid="stAppViewContainer"] {{ color: {INK}; }}

    /* headlines are the only serif on the page */
    h1, h2, h3, h4, h5, h6 {{
        font-family: {DISPLAY} !important;
        font-weight: 400 !important;
        color: {INK} !important;
        letter-spacing: -0.015em;
        line-height: 1.14;
        text-wrap: balance;
    }}
    h1 {{ font-size: clamp(2.1rem, 4.4vw, 3rem) !important; }}
    h5 {{ font-size: 1.5rem !important; margin-bottom: 0.15rem !important; }}

    /* everything that is read as text, rather than as a headline, is the
       grotesque. Prose sits at 16px with a generous measure. */
    [data-testid="stMarkdownContainer"] p,
    [data-testid="stMarkdownContainer"] li {{
        font-family: {SANS};
        font-size: 1rem;
        line-height: 1.62;
        color: {INK2};
    }}
    [data-testid="stMarkdownContainer"] strong {{
        color: {INK};
        font-weight: 600;
    }}
    [data-testid="stCaptionContainer"],
    [data-testid="stCaptionContainer"] p {{
        font-family: {SANS} !important;
        color: {QUIET} !important;
        font-size: 0.83rem !important;
        line-height: 1.58;
    }}
    /* digits are monospace and tabular wherever they carry meaning */
    [data-testid="stMetricValue"], [data-testid="stDataFrame"],
    .mono {{ font-variant-numeric: tabular-nums; }}

    /* eyebrow section label, hairline rule then uppercase tracking */
    .eyebrow {{
        font-family: {SANS};
        font-size: 0.68rem;
        font-weight: 600;
        letter-spacing: 0.16em;
        text-transform: uppercase;
        color: {QUIET};
        display: flex;
        align-items: center;
        gap: 0.65rem;
        margin: 2.2rem 0 0.8rem 0;
    }}
    .eyebrow::before {{
        content: "";
        width: 18px;
        height: 2px;
        background: currentColor;
        flex: 0 0 18px;
        opacity: 0.85;
    }}
    .eyebrow:first-child {{ margin-top: 0; }}

    /* Section panels. Streamlit owns the border wrapper and offers no way to
       put a class on it, so each panel reads its tone off the eyebrow inside
       it via :has(). Supported everywhere current; if a browser lacks it the
       panel simply falls back to the neutral border, which is the same
       result as before this treatment existed. */
    {TONE_CSS}

    [data-testid="stLayoutWrapper"] > [data-testid="stVerticalBlock"] {{
        border-radius: 6px;
        padding: 1.2rem 1.4rem 1.3rem;
    }}
    [data-testid="stLayoutWrapper"] {{ margin-bottom: 1.15rem; }}

    /* metrics: flat white panel, hairline, no shadow, figure in monospace */
    [data-testid="stMetric"] {{
        background: {CARD};
        border: 1px solid {GRID};
        border-radius: 4px;
        padding: 0.85rem 1rem;
    }}
    [data-testid="stMetricValue"] {{
        font-family: {MONO} !important;
        font-size: 1.55rem !important;
        letter-spacing: -0.03em;
        color: {CSF_BLUE};
        font-weight: 500;
    }}
    [data-testid="stMetricLabel"], [data-testid="stMetricLabel"] p {{
        font-family: {SANS} !important;
        font-size: 0.68rem !important;
        font-weight: 600 !important;
        letter-spacing: 0.09em;
        text-transform: uppercase;
        color: {QUIET} !important;
    }}
    [data-testid="stMetricDelta"] {{
        font-family: {MONO} !important;
        font-size: 0.76rem !important;
    }}

    .stTabs [data-baseweb="tab-list"] {{
        gap: 1.9rem;
        border-bottom: 1px solid {GRID};
    }}
    .stTabs [data-baseweb="tab"] {{
        font-family: {SANS};
        font-weight: 500;
        font-size: 0.78rem;
        letter-spacing: 0.09em;
        text-transform: uppercase;
        color: {QUIET};
        padding: 0.45rem 0;
    }}
    .stTabs [aria-selected="true"] {{ color: {CSF_BLUE}; }}
    /* the selected-tab underline. Streamlit 1.60 renders it via React Aria;
       the older baseweb node is kept so this survives either version */
    .stTabs .react-aria-SelectionIndicator,
    .stTabs [data-baseweb="tab-highlight"] {{ background: {CSF_BLUE} !important; }}

    /* the top toolbar strip sits above the app and defaults to white */
    [data-testid="stHeader"] {{ background: {PAPER}; }}

    [data-testid="stExpander"] details {{
        border: 1px solid {GRID};
        border-radius: 4px;
        background: {CARD};
    }}
    [data-testid="stExpander"] summary {{
        font-family: {SANS};
        font-size: 0.86rem;
        font-weight: 600;
        color: {INK2};
    }}
    [data-testid="stExpander"] summary:hover {{ color: {CSF_BLUE}; }}

    /* the story's opening line, the largest display moment in the app */
    .hero-kicker {{
        font-family: {DISPLAY};
        font-size: clamp(2.6rem, 6.4vw, 4.6rem);
        font-weight: 400;
        line-height: 1.0;
        letter-spacing: -0.03em;
        color: {INK};
        margin: 0.35rem 0 1rem 0;
        text-wrap: balance;
    }}

    /* controls: sans labels, hairline borders, no stock-Streamlit chrome */
    [data-testid="stWidgetLabel"] p {{
        font-family: {SANS} !important;
        font-size: 0.72rem !important;
        font-weight: 600 !important;
        letter-spacing: 0.08em;
        text-transform: uppercase;
        color: {INK2} !important;
    }}
    [data-baseweb="select"] > div,
    [data-testid="stMultiSelect"] > div > div {{
        font-family: {SANS};
        font-size: 0.86rem;
        background: {CARD};
        border-color: {GRID};
        border-radius: 4px;
    }}
    [data-baseweb="select"] > div:hover {{ border-color: {CSF_BLUE}; }}
    [data-baseweb="tag"] {{
        border-radius: 3px !important;
        font-family: {SANS};
        font-weight: 500;
        font-size: 0.78rem;
    }}
    [data-testid="stRadio"] label p,
    [data-testid="stCheckbox"] label p {{
        font-family: {SANS} !important;
        font-size: 0.86rem !important;
        color: {INK2} !important;
    }}
    [data-testid="stDownloadButton"] button,
    [data-testid="stBaseButton-secondary"] {{
        font-family: {SANS};
        font-size: 0.72rem;
        font-weight: 500;
        letter-spacing: 0.07em;
        text-transform: uppercase;
        border-radius: 4px;
        border: 1px solid {GRID};
        color: {INK2};
        background: {CARD};
    }}
    [data-testid="stDownloadButton"] button:hover {{
        border-color: {CSF_BLUE};
        color: {CSF_BLUE};
        background: {CARD};
    }}

    /* tables: hairline frame, square corners, figures in monospace */
    [data-testid="stDataFrame"] {{
        border: 1px solid {GRID};
        border-radius: 4px;
        overflow: hidden;
    }}
    [data-testid="stAlertContainer"] {{
        border-radius: 4px;
        font-family: {SANS};
    }}
    hr {{ border-color: {GRID}; }}
    </style>
    """, unsafe_allow_html=True)


def eyebrow(text, tone="plain"):
    st.markdown(f'<div class="eyebrow tone-{tone}">{text}</div>',
                unsafe_allow_html=True)


@contextmanager
def section(label, tone="plain"):
    """One titled, bordered panel.

    The tone reaches the panel through CSS :has() rather than through a class
    on the panel itself, because Streamlit owns the wrapper element and gives
    no hook to put a class on it. The eyebrow inside carries tone-<name> and
    the wrapper styles itself from that.
    """
    with st.container(border=True):
        eyebrow(label, tone)
        yield


@st.cache_data
def as_text(df, cols, spec, blank="no data", prefix=""):
    """Return a display copy with `cols` pre-rendered as text.

    A missing figure has to read as missing. Neither Styler.na_rep nor a
    callable formatter survives the trip through st.dataframe (the cell
    arrives from Arrow and paints as a literal "None"), so the substitution
    is done in the values themselves. The caller keeps the numeric frame for
    its CSV, which is what anyone recomputing should be using anyway.
    """
    out = df.copy()
    for c in cols:
        out[c] = df[c].map(
            lambda v: blank if pd.isna(v) else f"{prefix}{format(v, spec)}")
    return out


def right_align(styler, cols):
    return styler.set_properties(subset=cols, **{"text-align": "right"})


def table_csv(df, name, label="Download this table as CSV"):
    """Offer any displayed table as a CSV.

    Always pass the underlying DataFrame, never a Styler. utf-8-sig keeps
    the quality glyphs readable when the file is opened in Excel.
    """
    key = re.sub(r"[^A-Za-z0-9]+", "_", name).strip("_").lower()
    st.download_button(label, df.to_csv(index=False).encode("utf-8-sig"),
                       f"{name}.csv", "text/csv", key=f"dl_{key}")
